### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by doctorpepsis123** [Sam-DevZ/Discord-RoleReact#29]
Hi İ Am Bal10Man ,
 module.exports = {

	yourID: "600073926005096458",

	setupCMD: "++kayıt",

	deleteSetupCMD: false,

	initialMessage: ``,
	
	embedMessage: `Selam , Bot Olmadığını Doğrulamak İstiyorum . Kayıtlı Üye Rolü Almak İçin Aşağıdaki Emojilerden 5. Emojiye Tıklayın .`,

	embedFooter: "Emoji İle Kayıt Sistemi",
	
	roles: ["Eğer Botsan", "Eğer Botsan", "Eğer Botsan", "Eğer Botsan", "Kayıtlı Üye", "Eğer Botsan", "Eğer Botsan", "Eğer Botsan", "Eğer Botsan"],

	reactions: ["😅", "😅", "😅", "😅", "😎", "😅", "😅", "😅", "😅",],

	embed: true,

	embedColor: "#00FFFF",

	embedThumbnail: false,

	embedThumbnailLink: "",

	/**
	 * You"ll have to set this up yourself! Read more below:
	 * Please do not commit this token to the public if you contributed to this repository
	 * or host your code anywhere online. Giving someone your bot's token is the equivalent
	 * to giving someone the keys to your house and walking away!
	 * 
	 * https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
	 */
	botToken: "Special!"
};

I Get This Error:

C:\Users\marda\OneDrive\Masaüstü\Dosyalar\Discord-RoleReact-master\config.example.js:1
��m

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\marda\OneDrive\Masaüstü\Dosyalar\Discord-RoleReact-master\role.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-rolereact@2.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-rolereact@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marda\AppData\Roaming\npm-cache\_logs\2019-08-08T09_24_11_896Z-debug.log
PS C:\Users\marda\OneDrive\Masaüstü\Dosyalar\Discord-RoleReact-master>

**Comment by acollierr17** [comment]
Hi, this looks like a syntax error that you created when editing `config.example.js` file. 

I recommend you start from scratch and read the `README.md` file at the [base](https://github.com/Sam-DevZ/Discord-RoleReact) of the repository.

**Comment by cilsanirakesh** [comment]
HI am facing the below problem when ran npm install in my newly cloned SFRA project root directory .Kindly help me.

29600 verbose stack SyntaxError: Invalid or unexpected token
29600 verbose stack     at Module._compile (internal/modules/cjs/loader.js:720:23)
29600 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
29600 verbose stack     at Module.load (internal/modules/cjs/loader.js:643:32)
29600 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
29600 verbose stack     at Module.require (internal/modules/cjs/loader.js:683:19)
29600 verbose stack     at require (internal/modules/cjs/helpers.js:16:16)
29600 verbose stack     at initializeCache (C:\Program Files\nodejs\node_modules\npm\node_modules\make-fetch-happen\index.js:65:15)
29600 verbose stack     at configureOptions (C:\Program Files\nodejs\node_modules\npm\node_modules\make-fetch-happen\index.js:94:5)
29600 verbose stack     at cachingFetch (C:\Program Files\nodejs\node_modules\npm\node_modules\make-fetch-happen\index.js:107:16)
29600 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\index.js:76:50
29600 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
29600 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
29600 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
29600 verbose stack     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)
29600 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
29600 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
29601 verbose cwd C:\Users\cilsani.rakesh\git\storefront-reference-architecture
29602 verbose Windows_NT 10.0.16299
29603 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
29604 verbose node v12.6.0
29605 verbose npm  v6.9.0
29606 error Invalid or unexpected token
29607 verbose exit [ 1, true ]

**Comment by acollierr17** [comment]
Hi,

That seems to be a syntax error. When adjusting the config, you may have forgotten a double quote or something similar. Can you share the modifications you made to the config file?

**Comment by cilsanirakesh** [comment]
I have not done any modifications as such am just trying to install npm in root SFRA project directory.which config file your referring in the above comment.

**Comment by cilsanirakesh** [comment]
Ya I have increased the size of the cache in cache.js and some unwanted char entered without my knowledge causing the issue ..thank you it is resolved now.
