### ISSUE TITLE
Cannot read property 'animated' of undefined

### ISSUE THREAD

**Issue by SrPeterr** [Sam-DevZ/Discord-RoleReact#38]
**Describe the bug**
Console error

**To Reproduce**
1. execute !addreactions
2. Embed comes up
3. React with the emoji
4. Error on console and no role was given

**Expected behavior**
Give reole

**Screenshots**
`Unhandled Rejection TypeError: Cannot read property 'animated' of undefined
    at new Emoji (./node_modules/discord.js/src/structures/Emoji.js:17:27)
    at new ReactionEmoji (./node_modules/discord.js/src/structures/ReactionEmoji.js:14:5)
    at new MessageReaction (./node_modules/discord.js/src/structures/MessageReaction.js:43:19)
    at Client.<anonymous> (./bot.js:174:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

---

**Comment by LeManock** [comment]
Define it

**Comment by acollierr17** [comment]
Hi. Can you share your code changes so I can see what exactly you're doing?
> Define it

@LeManock This is not a helpful comment.

**Comment by KyberJeffHason** [comment]
same problem

**Comment by KyberJeffHason** [comment]
Example of what I am doing:
	roles: ["1", "2", "3"],

	/**
	 * For custom emojis, provide the name of the emoji
	 */
	reactions: ["458775940336582656", "458775940336582657", "458775940336582658"],

**Comment by ALCHElVlY** [comment]
Has anyone received a fix for this? I am also getting the error and the only thing I changed was putting the custom emoji name in the reactions field. Neither of these 2 emojis I added are animated .
